version: '3.8'

services:
  publisher:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-publisher
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    environment:
      - MTX_RTSPTRANSPORTS=tcp
      - MTX_WEBRTCADDITIONALHOSTS="localhost"
        #- MTX_PROTOCOLS_WEBRTC_ALLOWORIGIN=*
    ports:
      - "9998:9998"
      - "9999:9999"
      - "9997:9997"
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    tty: true
    stdin_open: true
    networks:
      - mediamtx_network

  dashboard:
    image: mediamtx-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MEDIAMTX_API_URL: ${NEXT_PUBLIC_MEDIAMTX_API_URL}
        NEXT_PUBLIC_MEDIAMTX_HLS_URL: ${NEXT_PUBLIC_MEDIAMTX_HLS_URL}
    container_name: mediamtx-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - publisher
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - mediamtx_network

  nginx_mediamtx:
    image: nginx:alpine
    container_name: nginx_mediamtx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "554:554"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx config file
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    depends_on:
      - publisher
      - dashboard
        # - grafana_mediamtx
        # - prometheus_mediamtx
        # - node-exporter_mediamtx
    networks:
      - mediamtx_network

  swagger_mediamtx:
    image: swaggerapi/swagger-ui
    container_name: mediamtx_swagger
    ports:
      - "8181:8080"
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml
    environment:
      - SWAGGER_JSON=/spec/openapi.yaml
    networks:
      - mediamtx_network

networks:
  mediamtx_network:
    name: mediamtx_network
