version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx-server-local
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "9997:9997"
      - "9998:9998"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    environment:
      - MTX_PROTOCOLS=tcp
    networks:
      - mediamtx-network

networks:
  mediamtx-network:
    driver: bridge
